#
# Makefile for the Smedia Glamo driver(s)
#

obj-$(CONFIG_DRM_GLAMO)			+= glamo-drm.o

glamo-drm-objs	:=  glamo-drm-drv.o glamo-cmdq.o glamo-buffer.o \
                    glamo-lcd.o glamo-fence.o \
                    glamo-crtc.o glamo-encoder.o glamo-connector.o \
                    glamo-mode-config.o glamo-fbdev.o glamo-fb.o \
                    glamo-framebuffer.o
