#
# Makefile for the Smedia Glamo driver(s)
#

obj-$(CONFIG_DRM_GLAMO)			+= glamo-drm.o

glamo-drm-objs	:=  glamo-drm-drv.o glamo-cmdq.o glamo-buffer.o \
                    glamo-display.o glamo-kms-fb.o glamo-fence.o
